config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # scope :admin do
  get 'dashboard', to: 'avo/tools#dashboard'
  # end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'

  }
  get '/posts/show/:id', to: 'posts#show', as: :show_post
  get '/posts', to: 'posts#index'
  get '/about', to: 'home#about', as: :about_page

  root 'home#index'
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
    resources :posts, only: %i[new create update destroy edit]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def about; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/about.html.erb
<div class = "card-body container">
  <div class = "jumbotron">
    <div class="col-5 mt-4  ">
      <div class="card text-center shadow mb-5  bg-white rounded">

        <h2 class = "main-text">About page </h2>
    <p>I'm glad you're here, this is a mini blog page.<br>
     What can you do on this page?<br>
You can to create, edit, delete your personal account,also
you can to write a post with a title, edit or delete it.
You can do all this from this page and also from the avo admin panel</p>

   <p class= "card=body"> <%=link_to 'Back to home page', root_path, class: "btn btn-dark" %></p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="text-center">Welcome!</h1><br>

<div class = "text-center">
<%=link_to "About page", about_page_path , class:"btn btn-dark"%>
<%=link_to "Avo Admin panel", avo_path , class:"btn btn-dark"%>
<%=link_to "Posts", posts_path , class:"btn btn-dark"%>
<%=link_to "New post", new_post_path , class:"btn btn-dark"%>
</div>